"""Pydantic schemas for API request/response models."""

from src.schemas.card import (
    AttackSchema,
    CardResponse,
    CardSummaryResponse,
    SetSummaryResponse,
)
from src.schemas.deck import (
    CardInDeck,
    DeckCreate,
    DeckImportRequest,
    DeckImportResponse,
    DeckResponse,
    DeckStatsResponse,
    DeckSummaryResponse,
    DeckUpdate,
    EnergyCurvePoint,
    TypeBreakdown,
    UnmatchedCard,
    UserSummary,
)
from src.schemas.format import (
    FormatConfigResponse,
    RotatingCard,
    RotationDetails,
    RotationImpactListResponse,
    RotationImpactResponse,
    UpcomingFormatResponse,
)
from src.schemas.lab_note import (
    LabNoteCreate,
    LabNoteListResponse,
    LabNoteResponse,
    LabNoteSummaryResponse,
    LabNoteUpdate,
)
from src.schemas.meta import (
    ArchetypeDetailResponse,
    ArchetypeHistoryPoint,
    ArchetypeResponse,
    CardUsageSummary,
    FormatNotes,
    JPSignals,
    KeyCardResponse,
    MatchupResponse,
    MatchupSpreadResponse,
    MetaHistoryResponse,
    MetaSnapshotResponse,
    SampleDeckResponse,
    TrendInfo,
)
from src.schemas.pagination import PaginatedResponse
from src.schemas.pipeline import (
    ComputeMetaRequest,
    ComputeMetaResult,
    PipelineRequest,
    ScrapeRequest,
    ScrapeResult,
    SyncCardsRequest,
    SyncCardsResult,
)
from src.schemas.set import SetResponse
from src.schemas.tournament import (
    ArchetypeMeta,
    BestOf,
    PlacementDetail,
    TopPlacement,
    TournamentDetailResponse,
    TournamentSummary,
    TournamentTier,
)
from src.schemas.usage import CardUsageResponse, UsageTrendPoint
from src.schemas.user import UserPreferencesUpdate, UserResponse

__all__ = [
    "ArchetypeDetailResponse",
    "ArchetypeHistoryPoint",
    "ArchetypeResponse",
    "AttackSchema",
    "BestOf",
    "CardInDeck",
    "CardResponse",
    "CardSummaryResponse",
    "CardUsageResponse",
    "CardUsageSummary",
    "ComputeMetaRequest",
    "ComputeMetaResult",
    "DeckCreate",
    "DeckImportRequest",
    "DeckImportResponse",
    "DeckResponse",
    "DeckStatsResponse",
    "DeckSummaryResponse",
    "DeckUpdate",
    "EnergyCurvePoint",
    "FormatConfigResponse",
    "FormatNotes",
    "JPSignals",
    "KeyCardResponse",
    "LabNoteCreate",
    "LabNoteListResponse",
    "LabNoteResponse",
    "LabNoteSummaryResponse",
    "LabNoteUpdate",
    "MatchupResponse",
    "MatchupSpreadResponse",
    "MetaHistoryResponse",
    "MetaSnapshotResponse",
    "PaginatedResponse",
    "PipelineRequest",
    "RotatingCard",
    "RotationDetails",
    "RotationImpactListResponse",
    "RotationImpactResponse",
    "SampleDeckResponse",
    "TrendInfo",
    "ScrapeRequest",
    "ScrapeResult",
    "SetResponse",
    "SetSummaryResponse",
    "SyncCardsRequest",
    "SyncCardsResult",
    "ArchetypeMeta",
    "PlacementDetail",
    "TopPlacement",
    "TournamentDetailResponse",
    "TournamentSummary",
    "TournamentTier",
    "TypeBreakdown",
    "UnmatchedCard",
    "UpcomingFormatResponse",
    "UsageTrendPoint",
    "UserPreferencesUpdate",
    "UserResponse",
    "UserSummary",
]
